[package]
name = "rocksdb-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.1.1"
rocksdb = "0.19.0"
serde = "1.0.152"
storekey = "0.3.0"
thiserror = "1.0.38"

[dev-dependencies]
anyhow = "1.0.68"
assert_fs = "1.0.10"
